// Generated by omo. Delete this file to stop loading the default global extension.
export { default } from "file:///Users/alpox/.local/lib/node_modules/omo-ai/node_modules/@code-yeongyu/senpi/dist/core/extensions/builtin/diff.js";
